# The west manifest file for Zephyr project.
#

manifest:
  defaults:
    remote: zephyr_site

  remotes:
    - name: zephyr_site
      url-base: https://github.com/zephyrproject-rtos
    - name: kabirz
      url-base: https://github.com/kabirz

  projects:
    - name: zephyr
      revision: v4.2.0
      path: zephyr
      import:
        name-allowlist:
          - hal_stm32
          - zcbor
          - mbedtls
          - cmsis
          - cmsis_6
          - fatfs
          - littlefs
          - segger

    - name: mcuboot
      revision: 27d7a6f1ab9a3a9a37887feb0bea387f9c63ef00
      remote: kabirz
      path: bootloader/mcuboot

  self:
    path: apps
